### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by kvv5150** [socprime/SigmaUI#1]
When exporting a valid sigma rule to any of the options available I am presented with a message that says "Something went wrong" None of the other options work. I am using Elastic Stack 6.4.2.

**Comment by jasonazzarella** [comment]
There's a lot of hardcoded stuff in here as part of the converting. 

Here are some tips based on looking at my logging from plugins/socprime_sigma_ui/server/translation_script/sigma/sigma_converter.log

A lot of stuff points back to files such as plugins/socprime_sigma_ui/server/translation_script/sigma/sigma_converter.py stating that it is looking for python in the wrong directories. Some of these are setup to specifically target /usr/bin/python3.6 or /usr/local/bin/python3.6. I went through all of them and changed them to my /usr/bin/python3 location which resolved the execution side.

You will also want to confirm where your kibana instance is as the execution will target /usr/share/kibana. I usually dump things in /opt/ so I had to fix that hardcoding as well. File location was plugins/socprime_sigma_ui/server/routes/sigma/get-translation.js 

Now everything is working a-ok :)

**Comment by kvv5150** [comment]
Do you remember which files in which directory point to the wrong Python version? I looked at the main python sigma.py script and changed it but there might be more. My kibana target is correct so I am good there.

**Comment by socprime** [comment]
Thank you for your report!
There are many things to fix in our app, thank you for your time to add this issue.
We have already added tasks to backlog for removing hard coded stuff from our app and will implement them as soon as possible.

**Comment by pritster5** [comment]
I'm still facing this issue after altering the python path to python 3 instead of python 3.6. Is the sigmac that is shipped with the plugin still valid?

**Comment by pritster5** [comment]
I have also updated the tools folder to use the latest files from https://github.com/SigmaHQ/sigma and the issue of "Something went wrong" still persists.

**Comment by pritster5** [comment]
Found the issue: In `/usr/share/kibana/plugins/socprime_sigma_ui/server/translation_script/sigma/` the `tmp_sigma.txt` and `sigma_converter.log` file don't have the necessary permissions by default, which causes sigmac to fail when called. 

You can fix this by chmod'ing them both to 755 (full permissions).

**Comment by pritster5** [comment]
Furthermore, ruamel.yaml NEEDS to be installed for sigmac.py to function correctly
