### ISSUE TITLE
"Plugin installation was unsuccessful due to error "No kibana plugins found in archive" "

### ISSUE THREAD

**Issue by pritster5** [socprime/SigmaUI#19]
I have Kibana 7.15.2 up and running and I've already modified the `package.json` file in the zip to reflect this version (kibana.version is set to 7.15.2) yet when I issue the command `/home/ubuntu# /usr/share/kibana/bin/./kibana-plugin install file:///home/ubuntu/sigma_ui_1.2.5.zip` I get the following error:

"Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by pritster5** [comment]
Solved: This plugin is incompatible with Kibana 7.10+. I downgraded to Kibana 7.6 and it installs the plugin fine.

**Comment by asadzz** [comment]
I'm using es/kibana 7.6  , but I'm getting error i tried with root and it gives me a different error
`Kibana should not be run as root.  Use --allow-root to continue`.


```
asad@elk:~$ /usr/share/kibana/bin/./kibana-plugin install file:///home/asad/sigma_ui_1.2.5.zip
Found previous install attempt. Deleting...
Babel could not write cache to file: /usr/share/kibana/optimize/.babel_register_cache.json 
due to a permission issue. Cache is disabled.
Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option."

```
