### ISSUE TITLE
ui.select load error

### ISSUE THREAD

**Issue by th-ink** [socprime/SigmaUI#5]
when using kibana 7.0.1., plugin load fails with:
```
Version: 7.0.1
Build: 23198
Error: [$injector:modulerr] Failed to instantiate module kibana due to:
[$injector:modulerr] Failed to instantiate module app/socprime_sigma_ui due to:
[$injector:modulerr] Failed to instantiate module ui.select due to:
[$injector:nomod] Module 'ui.select' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
error when opening the tab in kibana,

**Comment by socprime** [comment]
Kibana version 7 isn't supported by Sigma Ui plugin in this repository for the present moment,
but we plan to update the version of the application with new features in this repository

**Comment by Anna7835** [comment]
Is Kibana 7.4.2 is supported now?

**Comment by socprime** [comment]
Hello!
Thank you for your interest in our apps and  for your patience.
We have updated the Sigma UI to version 1.2.5.
Now it supports ELK stack up to version 7.6.1.
You can download it from this repository or from our Marketplace - [tdm.socprime.com](tdm.socprime.com)
