### ISSUE TITLE
when using kibana 5.3.3., plugin load fails with:

### ISSUE THREAD

**Issue by hungryforit** [socprime/SigmaUI#7]
「error」 :

Attempting to transfer from file:/opt/kibana-5.3.3-linux-x86_64/plugins/SigmaUI/sigma_ui_0.9.2.zip
Transferring 17203391 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [socprime_sigma_ui]. Expected [5.3.3]; found [6.6.1]"

「deal」:

Wait until the installation finishes, it may take few minutes to optimize and cache browser bundles. Restart Kibana to apply the changes

If you get error: “Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [sigmaui]. Expected [6.6.0]; found [6.6.1]“, please open zip archive and modify file “. /kibana/socprime_sigma_ui/package.json”: put version of your Kibana to field "kibana.version" ​
2. Restart Kibana to apply the changes.

In case after restart Kibana you don’t see any changes, go to /usr/share/kibana/optimize. Delete all files in the folder ‘optimize’ including subfolders. And restart Kibana.This will make Kibana to refresh it’s cache.

「Question」 :
After processing according to the official website, it still reports this error

**Comment by socprime** [comment]
Hello hungryforit!
Thank you for your interest in our apps
This version of Sigma UI requires at least ELK Stack version 6.2.3 and in file "/kibana/socprime_sigma_ui/package.json" in field "kibana.version" you should specify version of your ELK Stack
