### ISSUE TITLE
Error retrieving metadata from plugin archive

### ISSUE THREAD

**Issue by 10TOHH** [socprime/SigmaUI#8]
Not able to install the module due to error "Error retrieving metadata from plugin archive".

```
[content@localhost kibana-7.6.1]$ ./bin/kibana-plugin install file:///home/content/kibana-7.6.1/sigma_ui_1.2.5.zip 
Attempting to transfer from file:///home/content/kibana-7.6.1/sigma_ui_1.2.5.zip
Transferring 63620 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /home/content/kibana-7.6.1/node_modules/yauzl/index.js:187:14
    at /home/content/kibana-7.6.1/node_modules/yauzl/index.js:631:5
    at /home/content/kibana-7.6.1/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

**Comment by socprime** [comment]
Hello 10TOHH!
You can try another way to install the app. Unzip the archive **sigma_ui_1.2.5.zip**,
copy the folder **socprime_sigma_ui** (which is located in the **kibana** folder) to the folder **<path to your kibana>/kibana/plugins**
Then stop your Kibana
Delete the contents of the folder **<path to your kibana>/kibana/optimize** but do not delete the folder itself
Then start Kibana

This should help.
